name: NodeJS CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Install NodeJS
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install root
        run: npm ci
      - name: Install client
        run: npm --prefix ./packages/client ci
      - name: Lint
        run: npm run lint
      - name: Test client
        run: npm --prefix ./packages/client run test